In [1]:
import pandas as pd

In [4]:
data= pd.read_excel(r"C:\Users\light\Desktop\Data - Survey Monkey-Edited.xlsx", sheet_name= 'Edited_Data')

In [5]:
df_monkey= data.copy()

In [6]:
# understanding the data
df_monkey

,Respondent ID,Start Date,End Date,Email Address,First Name,Last Name,Custom Data 1,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,...,Question 29-Response 8,Question 29-Response 9,Question 29-Response 10,Question 29-Response 11,Question 29-Response 12,Question 29-Response 13,Question 29-Response 14,Question 30-Response 1,Question 30-Response 2,Question 30-Response 3
0,5379192392,2021-01-22 12:01:17,2021-01-22 12:40:34,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,Answer 8,Answer 8,Answer 4,NaN,NaN,Answer 5,NaN,NaN,NaN
1,2658722536,2021-01-22 06:56:37,2021-01-22 07:34:10,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,Answer 5,NaN,NaN,Answer 2,NaN,Answer 5,NaN,NaN,Answer 1
2,4044163394,2021-01-22 06:35:18,2021-01-22 06:47:32,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,NaN,NaN,Answer 4,Answer 4,Answer 6,NaN,Answer 6,NaN,Answer 1,NaN
3,5535865599,2021-01-21 21:29:32,2021-01-21 21:40:24,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 2,Answer 5,Answer 7,NaN,Answer 6,NaN,Answer 7,Answer 7,Answer 1,Answer 6
4,3356802928,2021-01-21 17:26:39,2021-01-21 17:44:40,NaN,NaN,NaN,NaN,Port Operations,NaN,Manager,...,NaN,Answer 5,Answer 4,Answer 4,Answer 7,Answer 7,NaN,Answer 7,NaN,Answer 8
5,3399511781,2021-01-21 11:40:13,2021-01-21 11:51:12,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,Answer 1,Answer 1,NaN,NaN,NaN,Answer 4,Answer 2,Answer 6,Answer 7,Answer 4
6,9860597462,2021-01-21 10:01:12,2021-01-21 10:48:07,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,NaN,Answer 5,Answer 2,Answer 5,NaN,Answer 1,NaN,NaN,NaN,Answer 1
7,1494621946,2021-01-21 09:48:29,2021-01-21 10:00:19,NaN,NaN,NaN,NaN,Infrastructure,NaN,Chief / Executive,...,NaN,Answer 4,NaN,NaN,NaN,NaN,NaN,Answer 7,Answer 3,Answer 6
8,8646387163,2021-01-21 09:16:50,2021-01-21 11:04:39,NaN,NaN,NaN,NaN,Information Technology,NaN,Manager,...,Answer 6,Answer 7,NaN,Answer 2,NaN,Answer 6,Answer 5,Answer 1,NaN,NaN
9,2455127238,2021-01-21 08:45:08,2021-01-21 09:00:52,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,Answer 3,Answer 4,Answer 7,Answer 1,Answer 1,NaN,NaN,NaN,Answer 5,NaN
10,1905266879,2021-01-21 07:54:44,2021-01-21 08:25:43,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 1,NaN,Answer 3,Answer 5,NaN,Answer 7,Answer 1,NaN,NaN,NaN
11,7089369660,2021-01-21 07:47:23,2021-01-21 07:48:27,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,Answer 3,Answer 2,NaN,NaN,NaN,Answer 7,NaN,Answer 1,Answer 3
12,3397360934,2021-01-21 07:40:11,2021-01-21 07:59:18,NaN,NaN,NaN,NaN,Legal,NaN,Staff,...,Answer 5,NaN,Answer 2,Answer 7,Answer 6,NaN,Answer 1,Answer 6,Answer 8,NaN
13,6904821010,2021-01-21 07:23:55,2021-01-21 07:57:44,NaN,NaN,NaN,NaN,Other (please specify),Construction,Staff,...,Answer 3,NaN,NaN,Answer 2,NaN,Answer 8,Answer 4,NaN,NaN,Answer 5
14,9961006444,2021-01-21 07:21:21,2021-01-21 07:22:22,NaN,NaN,NaN,NaN,Executive,NaN,Staff,...,Answer 1,NaN,Answer 1,NaN,NaN,Answer 5,NaN,Answer 2,Answer 8,Answer 4
15,9736526482,2021-01-21 06:49:32,2021-01-21 07:11:25,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 8,Answer 7,NaN,NaN,Answer 7,Answer 3,Answer 7,Answer 6,Answer 1,NaN
16,8035211358,2021-01-21 06:47:47,2021-01-21 06:57:50,NaN,NaN,NaN,NaN,Commercial,NaN,Manager,...,Answer 2,Answer 4,Answer 3,NaN,NaN,Answer 8,Answer 8,NaN,Answer 7,Answer 1
17,2855503402,2021-01-21 06:31:03,2021-01-21 07:01:02,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 7,Answer 3,NaN,Answer 6,Answer 7,NaN,Answer 8,Answer 4,Answer 2,Answer 4
18,4136037887,2021-01-21 06:22:53,2021-01-21 06:37:45,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 4,Answer 1,NaN,Answer 1,Answer 8,NaN,Answer 6,NaN,NaN,Answer 6
19,9624253323,2021-01-21 06:22:07,2021-01-21 06:23:30,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,Answer 4,Answer 2,NaN,NaN,NaN,Answer 4,NaN,Answer 8,Answer 6
20,8546027678,2021-01-21 06:13:00,2021-01-21 06:57:22,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,NaN,Answer 2,NaN,NaN,Answer 3,Answer 8,Answer 7,Answer 7,NaN
21,3555213031,2021-01-21 06:11:20,2021-01-21 06:24:11,NaN,NaN,NaN,NaN,Legal,NaN,Staff,...,Answer 3,Answer 4,Answer 6,Answer 2,Answer 8,Answer 6,NaN,Answer 2,NaN,Answer 3
22,1754220060,2021-01-20 20:39:00,2021-01-20 21:03:10,NaN,NaN,NaN,NaN,Finance,NaN,Department Lead,...,NaN,NaN,Answer 8,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN
23,9011744859,2021-01-20 14:53:14,2021-01-20 17:09:31,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,NaN,NaN,NaN,Answer 1,NaN,Answer 2,Answer 4,Answer 1,Answer 5,NaN
24,5875585727,2021-01-20 10:09:36,2021-01-20 10:29:29,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,Answer 4,Answer 7,Answer 4,Answer 4,Answer 3,Answer 5,Answer 7,NaN,Answer 6,NaN
25,9051604151,2021-01-20 05:41:50,2021-01-20 05:44:29,NaN,NaN,NaN,NaN,Commercial,NaN,Staff,...,NaN,NaN,Answer 6,NaN,NaN,Answer 3,NaN,Answer 1,NaN,NaN
26,6573346680,2021-01-16 13:31:12,2021-01-16 14:01:07,NaN,NaN,NaN,NaN,Commercial,NaN,Staff,...,NaN,Answer 5,Answer 4,NaN,Answer 7,Answer 4,NaN,Answer 8,NaN,NaN
27,4383571615,2021-01-15 16:35:26,2021-01-15 16:53:59,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,Answer 3,Answer 4,NaN,NaN,NaN,NaN,Answer 5,Answer 6,Answer 1,Answer 6
28,5850350235,2021-01-15 09:16:59,2021-01-15 09:18:36,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,Answer 6,Answer 7,Answer 2,Answer 2,Answer 3,Answer 1,NaN,Answer 5,Answer 8
29,9526771290,2021-01-15 09:12:23,2021-01-15 09:13:00,NaN,NaN,NaN,NaN,Port Operations,NaN,Manager,...,Answer 6,NaN,Answer 3,Answer 3,NaN,Answer 2,NaN,Answer 5,NaN,Answer 6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,3966690436,2021-01-11 06:36:47,2021-01-11 07:17:45,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,Answer 4,Answer 4,Answer 5,Answer 6,NaN,Answer 5,Answer 1,NaN,NaN
169,8630148625,2021-01-11 06:39:22,2021-01-11 06:47:54,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,Answer 7,Answer 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,1264208927,2021-01-11 06:32:43,2021-01-11 06:59:00,NaN,NaN,NaN,NaN,Port Security & Emergency Operations,NaN,Staff,...,Answer 8,Answer 2,NaN,Answer 1,NaN,Answer 5,Answer 2,NaN,Answer 3,NaN
171,9625886165,2021-01-11 06:33:15,2021-01-11 06:33:43,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,NaN,Answer 2,Answer 1,Answer 4,Answer 5,Answer 8,NaN,NaN,Answer 8,Answer 7
172,9351204267,2021-01-11 06:32:10,2021-01-11 06:49:36,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,Answer 3,Answer 3,NaN,NaN,Answer 5,NaN,Answer 1,NaN,Answer 7
173,1485638866,2021-01-11 06:31:39,2021-01-11 08:27:13,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,Answer 2,Answer 1,NaN,NaN,Answer 1,NaN,Answer 2,NaN,Answer 8,Answer 4
174,9137601822,2021-01-11 06:31:51,2021-01-11 06:50:34,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 1,Answer 6,NaN,NaN,NaN,Answer 3,Answer 3,NaN,Answer 4,NaN
175,4910729713,2021-01-11 06:32:21,2021-01-11 06:41:29,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 8,NaN,NaN,Answer 6,Answer 7,Answer 6,NaN,NaN,NaN,NaN
176,8453428178,2021-01-11 06:31:11,2021-01-11 07:01:11,NaN,NaN,NaN,NaN,Commercial,NaN,Manager,...,NaN,Answer 4,Answer 2,NaN,Answer 5,Answer 2,Answer 7,NaN,Answer 5,Answer 3
177,6903105973,2021-01-11 06:31:13,2021-01-11 06:44:41,NaN,NaN,NaN,NaN,Finance,NaN,Manager,...,Answer 8,Answer 1,Answer 2,Answer 3,NaN,NaN,NaN,NaN,Answer 7,NaN
178,2628194343,2021-01-11 06:29:29,2021-01-11 06:42:26,NaN,NaN,NaN,NaN,Executive,NaN,Staff,...,Answer 5,Answer 6,Answer 8,Answer 5,NaN,Answer 4,NaN,NaN,Answer 2,NaN
179,2254451126,2021-01-11 06:29:02,2021-01-11 06:30:09,NaN,NaN,NaN,NaN,Port Security & Emergency Operations,NaN,Staff,...,Answer 7,Answer 3,Answer 1,NaN,Answer 7,Answer 8,NaN,Answer 4,NaN,Answer 5
180,1426184525,2021-01-11 06:28:23,2021-01-11 06:47:34,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,Answer 8,Answer 6,NaN,Answer 4,NaN,NaN,NaN,Answer 6,NaN
181,1001882880,2021-01-11 06:28:52,2021-01-11 06:47:31,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,NaN,Answer 2,Answer 7,Answer 6,Answer 5,Answer 3,NaN,Answer 3,Answer 8
182,1941311372,2021-01-11 06:27:59,2021-01-14 13:20:12,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,NaN,NaN,NaN,Answer 8,Answer 7,NaN,NaN,Answer 1,Answer 6,Answer 2
183,8569413026,2021-01-11 06:27:34,2021-01-11 06:28:29,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 6,Answer 8,NaN,Answer 6,Answer 3,Answer 1,Answer 7,Answer 4,Answer 1,NaN
184,5953471955,2021-01-11 06:26:11,2021-01-11 06:41:40,NaN,NaN,NaN,NaN,People,NaN,Staff,...,NaN,NaN,Answer 7,NaN,Answer 7,NaN,Answer 8,Answer 7,Answer 8,Answer 1
185,3933988341,2021-01-11 06:26:52,2021-01-11 06:50:09,NaN,NaN,NaN,NaN,People,NaN,Staff,...,NaN,NaN,NaN,Answer 8,Answer 3,Answer 1,Answer 3,Answer 2,Answer 8,NaN
186,7963965247,2021-01-11 06:22:37,2021-01-11 06:34:03,NaN,NaN,NaN,NaN,Executive,NaN,Staff,...,NaN,Answer 7,Answer 8,Answer 2,Answer 1,Answer 4,NaN,NaN,NaN,NaN
187,9735550076,2021-01-11 06:21:24,2021-01-11 06:48:26,NaN,NaN,NaN,NaN,People,NaN,Staff,...,NaN,Answer 5,Answer 5,NaN,Answer 5,Answer 6,NaN,NaN,Answer 2,Answer 5
188,5559071396,2021-01-11 06:21:18,2021-01-11 06:35:53,NaN,NaN,NaN,NaN,Port Security & Emergency Operations,NaN,Staff,...,Answer 4,Answer 7,Answer 4,NaN,Answer 3,Answer 5,Answer 2,NaN,NaN,NaN
189,8253262223,2021-01-11 06:20:20,2021-01-11 06:39:07,NaN,NaN,NaN,NaN,People,NaN,Department Lead,...,NaN,NaN,NaN,Answer 5,NaN,NaN,Answer 5,NaN,NaN,NaN
190,7325851635,2021-01-11 06:20:29,2021-01-11 07:11:16,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,NaN,Answer 7,Answer 6,Answer 5,NaN,NaN,NaN,Answer 6,Answer 5,Answer 5
191,3370365802,2021-01-11 06:19:33,2021-01-11 06:39:01,NaN,NaN,NaN,NaN,Port Security & Emergency Operations,NaN,Staff,...,Answer 5,NaN,Answer 5,Answer 6,NaN,Answer 5,Answer 6,NaN,Answer 1,Answer 6
192,2841747833,2021-01-11 06:19:01,2021-01-11 06:35:13,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,NaN,NaN,NaN,Answer 8,Answer 6,NaN,Answer 5,Answer 6,NaN,NaN
193,7940065082,2021-01-11 06:19:18,2021-01-11 06:32:59,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,Answer 1,Answer 1,Answer 3,Answer 6,Answer 6,Answer 8,NaN,NaN,NaN,Answer 8
194,5157705612,2021-01-11 06:19:14,2021-01-11 06:33:29,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 5,NaN,Answer 5,NaN,NaN,Answer 2,NaN,NaN,NaN,Answer 6
195,9920755555,2021-01-11 06:18:48,2021-01-11 06:27:27,NaN,NaN,NaN,NaN,Port Operations,NaN,Staff,...,NaN,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN,Answer 3,NaN
196,6638341389,2021-01-11 06:19:01,2021-01-11 06:33:06,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 2,NaN,Answer 3,Answer 5,NaN,Answer 8,Answer 3,Answer 3,NaN,NaN
197,8114622230,2021-01-11 06:18:50,2021-01-11 06:26:46,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,Answer 3,NaN,Answer 7,NaN,NaN,NaN,NaN,Answer 3,NaN,NaN

In [7]:
df_monkey.shape

(198, 100)

In [8]:
df_monkey.columns

Index(['Respondent ID', 'Start Date', 'End Date', 'Email Address',
       'First Name', 'Last Name', 'Custom Data 1',
       'Identify which division you work in.-Response',
       'Identify which division you work in.-Other (please specify)',
       'Which of the following best describes your position level?-Response',
       'Which generation are you apart of?-Response',
       'Please select the gender in which you identify.-Response',
       'Which duration range best aligns with your tenure at your company?-Response',
       'Which of the following best describes your employment type?-Response',
       'Question 1-Response', 'Question 2-Response',
       'Question 3-Open-Ended Response', 'Question 4-Response',
       'Question 4-Other (please specify)', 'Question 5-Response 1',
       'Question 5-Response 2', 'Question 5-Response 3',
       'Question 5-Response 4', 'Question 5-Response 5',
       'Question 5-Response 6', 'Question 6-Response 1',
       'Question 6-Response 2', 'Question 6-Response 3',
       'Question 6-Response 4', 'Question 6-Response 5',
       'Question 6-Response 6', 'Question 7-Response 1',
       'Question 7-Unscheduled', 'Question 8-Response 1',
       'Question 8-Response 2', 'Question 8-Response 3',
       'Question 8-Response 4', 'Question 9-Response 1',
       'Question 9-Response 2', 'Question 9-Response 3',
       'Question 9-Response 4', 'Question 10-Response 1',
       'Question 10-Response 2', 'Question 10-Response 3',
       'Question 10-Response 4', 'Question 10-Response 5',
       'Question 11-Reponse 1', 'Question 11-Response 2',
       'Question 12-Response', 'Question 13-Response', 'Question 14-Response',
       'Question 15-Response', 'Question 16-Response', 'Question 17-Response',
       'Question 18-Response', 'Question 19-Response',
       'Question 19-Other (please specify)', 'Question 20-Response',
       'Question 21-Response', 'Question 22-Reponse 1',
       'Question 22-Reponse 2', 'Question 23-Response',
       'Question 24-Response 1', 'Question 24-Response 2',
       'Question 24-Response 3', 'Question 24-Response 4',
       'Question 24-Response 5', 'Question 25-Response 1',
       'Question 25-Response 2', 'Question 25-Response 3',
       'Question 25-Response 4', 'Question 25-Response 5',
       'Question 25-Response 6', 'Question 25-Response 7',
       'Question 25-Response 8', 'Question 25-Response 9',
       'Question 26-Response 1', 'Question 26-Response 2',
       'Question 26-Response 3', 'Question 26-Response 4',
       'Question 27-Response 1', 'Question 27-Response 2',
       'Question 28-Response', 'Question 29-Response 1',
       'Question 29-Response 2', 'Question 29-Response 3',
       'Question 29-Response 4', 'Question 29-Response 5',
       'Question 29-Response 6', 'Question 29-Response 7',
       'Question 29-Response 8', 'Question 29-Response 9',
       'Question 29-Response 10', 'Question 29-Response 11',
       'Question 29-Response 12', 'Question 29-Response 13',
       'Question 29-Response 14', 'Question 30-Response 1',
       'Question 30-Response 2', 'Question 30-Response 3'],
      dtype='object')

In [9]:
# dropping the unwanted columns:
df_monkey.drop(columns= ['Start Date', 'End Date', 'Email Address','First Name', 'Last Name', 'Custom Data 1'], inplace= True)

In [10]:
df_monkey

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question 1-Response,Question 2-Response,...,Question 29-Response 8,Question 29-Response 9,Question 29-Response 10,Question 29-Response 11,Question 29-Response 12,Question 29-Response 13,Question 29-Response 14,Question 30-Response 1,Question 30-Response 2,Question 30-Response 3
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,NaN,Answer 6,...,NaN,Answer 8,Answer 8,Answer 4,NaN,NaN,Answer 5,NaN,NaN,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Answer 4,Answer 2,...,NaN,Answer 5,NaN,NaN,Answer 2,NaN,Answer 5,NaN,NaN,Answer 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Answer 5,Answer 7,...,NaN,NaN,Answer 4,Answer 4,Answer 6,NaN,Answer 6,NaN,Answer 1,NaN
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Answer 1,Answer 1,...,Answer 2,Answer 5,Answer 7,NaN,Answer 6,NaN,Answer 7,Answer 7,Answer 1,Answer 6
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,NaN,Answer 3,...,NaN,Answer 5,Answer 4,Answer 4,Answer 7,Answer 7,NaN,Answer 7,NaN,Answer 8
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Answer 8,Answer 6,...,Answer 1,Answer 1,NaN,NaN,NaN,Answer 4,Answer 2,Answer 6,Answer 7,Answer 4
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Answer 8,Answer 2,...,NaN,Answer 5,Answer 2,Answer 5,NaN,Answer 1,NaN,NaN,NaN,Answer 1
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,NaN,Answer 5,...,NaN,Answer 4,NaN,NaN,NaN,NaN,NaN,Answer 7,Answer 3,Answer 6
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Answer 3,Answer 7,...,Answer 6,Answer 7,NaN,Answer 2,NaN,Answer 6,Answer 5,Answer 1,NaN,NaN
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Answer 4,Answer 5,...,Answer 3,Answer 4,Answer 7,Answer 1,Answer 1,NaN,NaN,NaN,Answer 5,NaN
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,NaN,NaN,...,Answer 1,NaN,Answer 3,Answer 5,NaN,Answer 7,Answer 1,NaN,NaN,NaN
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Answer 2,Answer 6,...,NaN,Answer 3,Answer 2,NaN,NaN,NaN,Answer 7,NaN,Answer 1,Answer 3
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Answer 7,Answer 3,...,Answer 5,NaN,Answer 2,Answer 7,Answer 6,NaN,Answer 1,Answer 6,Answer 8,NaN
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Answer 5,Answer 1,...,Answer 3,NaN,NaN,Answer 2,NaN,Answer 8,Answer 4,NaN,NaN,Answer 5
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,NaN,NaN,...,Answer 1,NaN,Answer 1,NaN,NaN,Answer 5,NaN,Answer 2,Answer 8,Answer 4
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,NaN,Answer 1,...,Answer 8,Answer 7,NaN,NaN,Answer 7,Answer 3,Answer 7,Answer 6,Answer 1,NaN
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Answer 1,Answer 4,...,Answer 2,Answer 4,Answer 3,NaN,NaN,Answer 8,Answer 8,NaN,Answer 7,Answer 1
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,NaN,Answer 4,...,Answer 7,Answer 3,NaN,Answer 6,Answer 7,NaN,Answer 8,Answer 4,Answer 2,Answer 4
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Answer 3,NaN,...,Answer 4,Answer 1,NaN,Answer 1,Answer 8,NaN,Answer 6,NaN,NaN,Answer 6
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Answer 3,Answer 3,...,NaN,Answer 4,Answer 2,NaN,NaN,NaN,Answer 4,NaN,Answer 8,Answer 6
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,NaN,NaN,...,NaN,NaN,Answer 2,NaN,NaN,Answer 3,Answer 8,Answer 7,Answer 7,NaN
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Answer 3,NaN,...,Answer 3,Answer 4,Answer 6,Answer 2,Answer 8,Answer 6,NaN,Answer 2,NaN,Answer 3
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Answer 4,Answer 2,...,NaN,NaN,Answer 8,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Answer 2,NaN,...,NaN,NaN,NaN,Answer 1,NaN,Answer 2,Answer 4,Answer 1,Answer 5,NaN
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Answer 1,NaN,...,Answer 4,Answer 7,Answer 4,Answer 4,Answer 3,Answer 5,Answer 7,NaN,Answer 6,NaN
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,NaN,NaN,...,NaN,NaN,Answer 6,NaN,NaN,Answer 3,NaN,Answer 1,NaN,NaN
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,NaN,Answer 1,...,NaN,Answer 5,Answer 4,NaN,Answer 7,Answer 4,NaN,Answer 8,NaN,NaN
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Answer 5,Answer 6,...,Answer 3,Answer 4,NaN,NaN,NaN,NaN,Answer 5,Answer 6,Answer 1,Answer 6
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,NaN,NaN,...,NaN,Answer 6,Answer 7,Answer 2,Answer 2,Answer 3,Answer 1,NaN,Answer 5,Answer 8
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Answer 2,NaN,...,Answer 6,NaN,Answer 3,Answer 3,NaN,Answer 2,NaN,Answer 5,NaN,Answer 6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Answer 8,Answer 2,...,NaN,Answer 4,Answer 4,Answer 5,Answer 6,NaN,Answer 5,Answer 1,NaN,NaN
169,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Answer 6,Answer 1,...,Answer 7,Answer 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Answer 8,NaN,...,Answer 8,Answer 2,NaN,Answer 1,NaN,Answer 5,Answer 2,NaN,Answer 3,NaN
171,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Answer 8,NaN,...,NaN,Answer 2,Answer 1,Answer 4,Answer 5,Answer 8,NaN,NaN,Answer 8,Answer 7
172,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,NaN,NaN,...,NaN,Answer 3,Answer 3,NaN,NaN,Answer 5,NaN,Answer 1,NaN,Answer 7
173,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Answer 6,Answer 5,...,Answer 2,Answer 1,NaN,NaN,Answer 1,NaN,Answer 2,NaN,Answer 8,Answer 4
174,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Answer 3,Answer 7,...,Answer 1,Answer 6,NaN,NaN,NaN,Answer 3,Answer 3,NaN,Answer 4,NaN
175,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,NaN,Answer 6,...,Answer 8,NaN,NaN,Answer 6,Answer 7,Answer 6,NaN,NaN,NaN,NaN
176,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Answer 5,NaN,...,NaN,Answer 4,Answer 2,NaN,Answer 5,Answer 2,Answer 7,NaN,Answer 5,Answer 3
177,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Answer 8,NaN,...,Answer 8,Answer 1,Answer 2,Answer 3,NaN,NaN,NaN,NaN,Answer 7,NaN
178,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Answer 6,Answer 6,...,Answer 5,Answer 6,Answer 8,Answer 5,NaN,Answer 4,NaN,NaN,Answer 2,NaN
179,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Answer 4,NaN,...,Answer 7,Answer 3,Answer 1,NaN,Answer 7,Answer 8,NaN,Answer 4,NaN,Answer 5
180,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Answer 5,Answer 8,...,NaN,Answer 8,Answer 6,NaN,Answer 4,NaN,NaN,NaN,Answer 6,NaN
181,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Answer 7,NaN,...,NaN,NaN,Answer 2,Answer 7,Answer 6,Answer 5,Answer 3,NaN,Answer 3,Answer 8
182,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Answer 6,Answer 6,...,NaN,NaN,NaN,Answer 8,Answer 7,NaN,NaN,Answer 1,Answer 6,Answer 2
183,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,NaN,Answer 6,...,Answer 6,Answer 8,NaN,Answer 6,Answer 3,Answer 1,Answer 7,Answer 4,Answer 1,NaN
184,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,NaN,Answer 3,...,NaN,NaN,Answer 7,NaN,Answer 7,NaN,Answer 8,Answer 7,Answer 8,Answer 1
185,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,NaN,NaN,...,NaN,NaN,NaN,Answer 8,Answer 3,Answer 1,Answer 3,Answer 2,Answer 8,NaN
186,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Answer 3,Answer 7,...,NaN,Answer 7,Answer 8,Answer 2,Answer 1,Answer 4,NaN,NaN,NaN,NaN
187,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,NaN,NaN,...,NaN,Answer 5,Answer 5,NaN,Answer 5,Answer 6,NaN,NaN,Answer 2,Answer 5
188,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Answer 1,Answer 5,...,Answer 4,Answer 7,Answer 4,NaN,Answer 3,Answer 5,Answer 2,NaN,NaN,NaN
189,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,NaN,Answer 3,...,NaN,NaN,NaN,Answer 5,NaN,NaN,Answer 5,NaN,NaN,NaN
190,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Answer 7,Answer 1,...,NaN,Answer 7,Answer 6,Answer 5,NaN,NaN,NaN,Answer 6,Answer 5,Answer 5
191,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,NaN,Answer 7,...,Answer 5,NaN,Answer 5,Answer 6,NaN,Answer 5,Answer 6,NaN,Answer 1,Answer 6
192,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Answer 3,Answer 6,...,NaN,NaN,NaN,Answer 8,Answer 6,NaN,Answer 5,Answer 6,NaN,NaN
193,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Answer 3,NaN,...,Answer 1,Answer 1,Answer 3,Answer 6,Answer 6,Answer 8,NaN,NaN,NaN,Answer 8
194,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,NaN,NaN,...,Answer 5,NaN,Answer 5,NaN,NaN,Answer 2,NaN,NaN,NaN,Answer 6
195,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,NaN,Answer 7,...,NaN,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN,Answer 3,NaN
196,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,NaN,NaN,...,Answer 2,NaN,Answer 3,Answer 5,NaN,Answer 8,Answer 3,Answer 3,NaN,NaN
197,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,NaN,Answer 1,...,Answer 3,NaN,Answer 7,NaN,NaN,NaN,NaN,Answer 3,NaN,NaN

In [11]:
column_list= list(df_monkey.columns)
column_list

['Respondent ID',
 'Identify which division you work in.-Response',
 'Identify which division you work in.-Other (please specify)',
 'Which of the following best describes your position level?-Response',
 'Which generation are you apart of?-Response',
 'Please select the gender in which you identify.-Response',
 'Which duration range best aligns with your tenure at your company?-Response',
 'Which of the following best describes your employment type?-Response',
 'Question 1-Response',
 'Question 2-Response',
 'Question 3-Open-Ended Response',
 'Question 4-Response',
 'Question 4-Other (please specify)',
 'Question 5-Response 1',
 'Question 5-Response 2',
 'Question 5-Response 3',
 'Question 5-Response 4',
 'Question 5-Response 5',
 'Question 5-Response 6',
 'Question 6-Response 1',
 'Question 6-Response 2',
 'Question 6-Response 3',
 'Question 6-Response 4',
 'Question 6-Response 5',
 'Question 6-Response 6',
 'Question 7-Response 1',
 'Question 7-Unscheduled',
 'Question 8-Response 1',
 'Question 8-Response 2',
 'Question 8-Response 3',
 'Question 8-Response 4',
 'Question 9-Response 1',
 'Question 9-Response 2',
 'Question 9-Response 3',
 'Question 9-Response 4',
 'Question 10-Response 1',
 'Question 10-Response 2',
 'Question 10-Response 3',
 'Question 10-Response 4',
 'Question 10-Response 5',
 'Question 11-Reponse 1',
 'Question 11-Response 2',
 'Question 12-Response',
 'Question 13-Response',
 'Question 14-Response',
 'Question 15-Response',
 'Question 16-Response',
 'Question 17-Response',
 'Question 18-Response',
 'Question 19-Response',
 'Question 19-Other (please specify)',
 'Question 20-Response',
 'Question 21-Response',
 'Question 22-Reponse 1',
 'Question 22-Reponse 2',
 'Question 23-Response',
 'Question 24-Response 1',
 'Question 24-Response 2',
 'Question 24-Response 3',
 'Question 24-Response 4',
 'Question 24-Response 5',
 'Question 25-Response 1',
 'Question 25-Response 2',
 'Question 25-Response 3',
 'Question 25-Response 4',
 'Question 25-Response 5',
 'Question 25-Response 6',
 'Question 25-Response 7',
 'Question 25-Response 8',
 'Question 25-Response 9',
 'Question 26-Response 1',
 'Question 26-Response 2',
 'Question 26-Response 3',
 'Question 26-Response 4',
 'Question 27-Response 1',
 'Question 27-Response 2',
 'Question 28-Response',
 'Question 29-Response 1',
 'Question 29-Response 2',
 'Question 29-Response 3',
 'Question 29-Response 4',
 'Question 29-Response 5',
 'Question 29-Response 6',
 'Question 29-Response 7',
 'Question 29-Response 8',
 'Question 29-Response 9',
 'Question 29-Response 10',
 'Question 29-Response 11',
 'Question 29-Response 12',
 'Question 29-Response 13',
 'Question 29-Response 14',
 'Question 30-Response 1',
 'Question 30-Response 2',
 'Question 30-Response 3']

In [12]:
vars= column_list[:8]
vars

['Respondent ID',
 'Identify which division you work in.-Response',
 'Identify which division you work in.-Other (please specify)',
 'Which of the following best describes your position level?-Response',
 'Which generation are you apart of?-Response',
 'Please select the gender in which you identify.-Response',
 'Which duration range best aligns with your tenure at your company?-Response',
 'Which of the following best describes your employment type?-Response']

In [13]:
val= column_list[8:]
val

['Question 1-Response',
 'Question 2-Response',
 'Question 3-Open-Ended Response',
 'Question 4-Response',
 'Question 4-Other (please specify)',
 'Question 5-Response 1',
 'Question 5-Response 2',
 'Question 5-Response 3',
 'Question 5-Response 4',
 'Question 5-Response 5',
 'Question 5-Response 6',
 'Question 6-Response 1',
 'Question 6-Response 2',
 'Question 6-Response 3',
 'Question 6-Response 4',
 'Question 6-Response 5',
 'Question 6-Response 6',
 'Question 7-Response 1',
 'Question 7-Unscheduled',
 'Question 8-Response 1',
 'Question 8-Response 2',
 'Question 8-Response 3',
 'Question 8-Response 4',
 'Question 9-Response 1',
 'Question 9-Response 2',
 'Question 9-Response 3',
 'Question 9-Response 4',
 'Question 10-Response 1',
 'Question 10-Response 2',
 'Question 10-Response 3',
 'Question 10-Response 4',
 'Question 10-Response 5',
 'Question 11-Reponse 1',
 'Question 11-Response 2',
 'Question 12-Response',
 'Question 13-Response',
 'Question 14-Response',
 'Question 15-Response',
 'Question 16-Response',
 'Question 17-Response',
 'Question 18-Response',
 'Question 19-Response',
 'Question 19-Other (please specify)',
 'Question 20-Response',
 'Question 21-Response',
 'Question 22-Reponse 1',
 'Question 22-Reponse 2',
 'Question 23-Response',
 'Question 24-Response 1',
 'Question 24-Response 2',
 'Question 24-Response 3',
 'Question 24-Response 4',
 'Question 24-Response 5',
 'Question 25-Response 1',
 'Question 25-Response 2',
 'Question 25-Response 3',
 'Question 25-Response 4',
 'Question 25-Response 5',
 'Question 25-Response 6',
 'Question 25-Response 7',
 'Question 25-Response 8',
 'Question 25-Response 9',
 'Question 26-Response 1',
 'Question 26-Response 2',
 'Question 26-Response 3',
 'Question 26-Response 4',
 'Question 27-Response 1',
 'Question 27-Response 2',
 'Question 28-Response',
 'Question 29-Response 1',
 'Question 29-Response 2',
 'Question 29-Response 3',
 'Question 29-Response 4',
 'Question 29-Response 5',
 'Question 29-Response 6',
 'Question 29-Response 7',
 'Question 29-Response 8',
 'Question 29-Response 9',
 'Question 29-Response 10',
 'Question 29-Response 11',
 'Question 29-Response 12',
 'Question 29-Response 13',
 'Question 29-Response 14',
 'Question 30-Response 1',
 'Question 30-Response 2',
 'Question 30-Response 3']

In [14]:
# melting the data so we have more rows then columns:

df_monkey_melted= df_monkey.melt(id_vars= vars, value_vars= val, var_name= 'Questions_&_Subquestions', value_name='Answers')

In [15]:
df_monkey_melted

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Questions_&_Subquestions,Answers
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 8
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 8
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1-Response,NaN
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,Answer 3
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 4
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1-Response,NaN
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1-Response,Answer 2
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1-Response,Answer 7
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 5
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1-Response,NaN
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1-Response,Answer 1
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,Answer 3
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 3
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,NaN
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,Answer 3
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 4
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 2
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 1
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,NaN
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 5
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,NaN
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 2
...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,NaN
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 7
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,Answer 7
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 4
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 3
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 5
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 8
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 2
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 1
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 5
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30-Response 3,NaN
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30-Response 3,Answer 5
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 6
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN

In [16]:
# renaming some of the columns:

df_monkey_melted.rename(columns= {'Identify which division you work in. - Response' : 'Division', 
                                  'Identify which division you work in. - Other (please specify)' : 'Division(Other)', 
                                  'Which of the following best describes your position level? - Response' : 'Position_Level', 
                                  'Which generation are you apart of? - Response' : 'Generation', 
                                  'Please select the gender in which you identify. - Response' : 'Gender',
                                  'Which duration range best aligns with your tenure at your company? - Response' : 'Tenure',
                                  'Which of the following best describes your employment type? - Response' : 'Employment_Type'},
                       inplace= True)

In [17]:
df_monkey_melted

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Questions_&_Subquestions,Answers
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 8
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 8
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1-Response,NaN
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,Answer 3
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 4
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1-Response,NaN
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1-Response,Answer 2
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1-Response,Answer 7
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 5
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1-Response,NaN
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1-Response,Answer 1
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,Answer 3
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 3
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,NaN
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,Answer 3
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 4
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 2
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 1
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,NaN
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 5
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,NaN
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 2
...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,NaN
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 7
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,Answer 7
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 4
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 3
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 5
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 8
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 2
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 1
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 5
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30-Response 3,NaN
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30-Response 3,Answer 5
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 6
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN

In [18]:
# importing the Questions sheet
df_questions= pd.read_excel(r"C:\Users\light\Desktop\Data - Survey Monkey-Edited.xlsx", sheet_name= 'Questions')

In [19]:
df_questions

,Raw_Questions,Raw_Subquestions,Questions,Subquestion,Questions_&_Subquestions
0,Respondent ID,NaN,Respondent ID,NaN,Respondent ID
1,Start Date,NaN,Start Date,NaN,Start Date
2,End Date,NaN,End Date,NaN,End Date
3,Email Address,NaN,Email Address,NaN,Email Address
4,First Name,NaN,First Name,NaN,First Name
5,Last Name,NaN,Last Name,NaN,Last Name
6,Custom Data 1,NaN,Custom Data 1,NaN,Custom Data 1
7,Identify which division you work in.,Response,Identify which division you work in.,Response,Identify which division you work in.-Response
8,NaN,Other (please specify),Identify which division you work in.,Other (please specify),Identify which division you work in.-Other (please specify)
9,Which of the following best describes your position level?,Response,Which of the following best describes your position level?,Response,Which of the following best describes your position level?-Response
10,Which generation are you apart of?,Response,Which generation are you apart of?,Response,Which generation are you apart of?-Response
11,Please select the gender in which you identify.,Response,Please select the gender in which you identify.,Response,Please select the gender in which you identify.-Response
12,Which duration range best aligns with your tenure at your company?,Response,Which duration range best aligns with your tenure at your company?,Response,Which duration range best aligns with your tenure at your company?-Response
13,Which of the following best describes your employment type?,Response,Which of the following best describes your employment type?,Response,Which of the following best describes your employment type?-Response
14,Question 1,Response,Question 1,Response,Question 1-Response
15,Question 2,Response,Question 2,Response,Question 2-Response
16,Question 3,Open-Ended Response,Question 3,Open-Ended Response,Question 3-Open-Ended Response
17,Question 4,Response,Question 4,Response,Question 4-Response
18,NaN,Other (please specify),Question 4,Other (please specify),Question 4-Other (please specify)
19,Question 5,Response 1,Question 5,Response 1,Question 5-Response 1
20,NaN,Response 2,Question 5,Response 2,Question 5-Response 2
21,NaN,Response 3,Question 5,Response 3,Question 5-Response 3
22,NaN,Response 4,Question 5,Response 4,Question 5-Response 4
23,NaN,Response 5,Question 5,Response 5,Question 5-Response 5
24,NaN,Response 6,Question 5,Response 6,Question 5-Response 6
25,Question 6,Response 1,Question 6,Response 1,Question 6-Response 1
26,NaN,Response 2,Question 6,Response 2,Question 6-Response 2
27,NaN,Response 3,Question 6,Response 3,Question 6-Response 3
28,NaN,Response 4,Question 6,Response 4,Question 6-Response 4
29,NaN,Response 5,Question 6,Response 5,Question 6-Response 5
...,...,...,...,...,...
70,NaN,Response 4,Question 25,Response 4,Question 25-Response 4
71,NaN,Response 5,Question 25,Response 5,Question 25-Response 5
72,NaN,Response 6,Question 25,Response 6,Question 25-Response 6
73,NaN,Response 7,Question 25,Response 7,Question 25-Response 7
74,NaN,Response 8,Question 25,Response 8,Question 25-Response 8
75,NaN,Response 9,Question 25,Response 9,Question 25-Response 9
76,Question 26,Response 1,Question 26,Response 1,Question 26-Response 1
77,NaN,Response 2,Question 26,Response 2,Question 26-Response 2
78,NaN,Response 3,Question 26,Response 3,Question 26-Response 3
79,NaN,Response 4,Question 26,Response 4,Question 26-Response 4
80,Question 27,Response 1,Question 27,Response 1,Question 27-Response 1
81,NaN,Response 2,Question 27,Response 2,Question 27-Response 2
82,Question 28,Response,Question 28,Response,Question 28-Response
83,Question 29,Response 1,Question 29,Response 1,Question 29-Response 1
84,NaN,Response 2,Question 29,Response 2,Question 29-Response 2
85,NaN,Response 3,Question 29,Response 3,Question 29-Response 3
86,NaN,Response 4,Question 29,Response 4,Question 29-Response 4
87,NaN,Response 5,Question 29,Response 5,Question 29-Response 5
88,NaN,Response 6,Question 29,Response 6,Question 29-Response 6
89,NaN,Response 7,Question 29,Response 7,Question 29-Response 7
90,NaN,Response 8,Question 29,Response 8,Question 29-Response 8
91,NaN,Response 9,Question 29,Response 9,Question 29-Response 9
92,NaN,Response 10,Question 29,Response 10,Question 29-Response 10
93,NaN,Response 11,Question 29,Response 11,Question 29-Response 11
94,NaN,Response 12,Question 29,Response 12,Question 29-Response 12
95,NaN,Response 13,Question 29,Response 13,Question 29-Response 13
96,NaN,Response 14,Question 29,Response 14,Question 29-Response 14
97,Question 30,Response 1,Question 30,Response 1,Question 30-Response 1
98,NaN,Response 2,Question 30,Response 2,Question 30-Response 2
99,NaN,Response 3,Question 30,Response 3,Question 30-Response 3

In [20]:
# dropping unwanted columns from df_questions

df_questions.drop(columns= ['Raw_Questions', 'Raw_Subquestions', 'Subquestion'], inplace= True)

In [21]:
df_questions

        Questions Questions_&_Subquestions
0   Respondent ID            Respondent ID
1      Start Date               Start Date
2        End Date                 End Date
3   Email Address            Email Address
4      First Name               First Name
..            ...                      ...
95    Question 29  Question 29-Response 13
96    Question 29  Question 29-Response 14
97    Question 30   Question 30-Response 1
98    Question 30   Question 30-Response 2
99    Question 30   Question 30-Response 3

[100 rows x 2 columns]

In [45]:
# Merging this columns to the 'df_monkey_melted' table:

df_monkey_melted_1= pd.merge(left= df_monkey_melted, right= df_questions, left_on= 'Questions_&_Subquestions', right_on='Questions_&_Subquestions', how= 'left')

In [46]:
# creating checkpoint
df_monkey_Edited= df_monkey_melted_1
df_monkey_Edited

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Questions_&_Subquestions,Answers,Questions
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 8,Question 1
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 8,Question 1
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1-Response,NaN,Question 1
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,Answer 3,Question 1
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 4,Question 1
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1-Response,Answer 2,Question 1
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1-Response,Answer 7,Question 1
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 5,Question 1
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,Answer 3,Question 1
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 3,Question 1
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,Answer 3,Question 1
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 4,Question 1
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 2,Question 1
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 1,Question 1
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 5,Question 1
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,NaN,Question 1
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 2,Question 1
...,...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 7,Question 30
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,Answer 7,Question 30
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 4,Question 30
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 3,Question 30
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 5,Question 30
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 8,Question 30
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 2,Question 30
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 1,Question 30
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 5,Question 30
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30-Response 3,Answer 5,Question 30
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30

In [47]:
# renaming some columns:

df_monkey_Edited.rename(columns= {'Identify which division you work in.-Response' : 'Division',
                                  'Identify which division you work in.-Other (please specify)' : 'Division(Other)',
                                  'Which of the following best describes your position level?-Response': 'Position_Level',
                                  'Which generation are you apart of?-Response' : 'Generation',
                                  'Please select the gender in which you identify.-Response' : 'Gender',
                                  'Which duration range best aligns with your tenure at your company?-Response' : 'Tenure',
                                  'Which of the following best describes your employment type?-Response' : 'Employment_Type'},
                       inplace= True)

In [48]:
df_monkey_Edited

,Respondent ID,Division,Division(Other),Position_Level,Generation,Gender,Tenure,Employment_Type,Questions_&_Subquestions,Answers,Questions
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 8,Question 1
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 8,Question 1
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1-Response,NaN,Question 1
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,Answer 3,Question 1
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 4,Question 1
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1-Response,Answer 2,Question 1
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1-Response,Answer 7,Question 1
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 5,Question 1
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,Answer 3,Question 1
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1-Response,Answer 3,Question 1
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1-Response,Answer 3,Question 1
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 4,Question 1
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1-Response,Answer 2,Question 1
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 1,Question 1
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1-Response,Answer 5,Question 1
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,NaN,Question 1
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1-Response,Answer 2,Question 1
...,...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 7,Question 30
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,Answer 7,Question 30
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 4,Question 30
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 3,Question 30
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,Answer 5,Question 30
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 8,Question 30
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 2,Question 30
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 1,Question 30
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30-Response 3,NaN,Question 30
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30-Response 3,Answer 5,Question 30
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30-Response 3,Answer 5,Question 30
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30

In [50]:
# rearranging some columns:
df_monkey_Edited= df_monkey_Edited.loc[:, ['Respondent ID', 'Division', 'Division(Other)', 'Position_Level', 
                 'Generation', 'Gender', 'Tenure', 'Employment_Type', 'Questions', 'Questions_&_Subquestions', 'Answers']]

In [51]:
df_monkey_Edited

,Respondent ID,Division,Division(Other),Position_Level,Generation,Gender,Tenure,Employment_Type,Questions,Questions_&_Subquestions,Answers
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 4
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 5
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 8
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 8
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,NaN
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 4
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 2
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 7
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 5
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 4
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 2
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 1
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 5
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,NaN
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 2
...,...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 7
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 7
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 3
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 8
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 1
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 8
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN

In [52]:
df_monkey_Edited.shape

(17028, 11)

In [69]:
# Calculating questions answerd by number of respondent:

df_answered= df_monkey_Edited[df_monkey_Edited['Answers'].notna()]

In [70]:
df_answered

,Respondent ID,Division,Division(Other),Position_Level,Generation,Gender,Tenure,Employment_Type,Questions,Questions_&_Subquestions,Answers
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 4
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 5
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 8
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 8
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 4
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 2
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 7
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 5
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 4
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 2
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 1
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 5
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 2
31,3087114007,Information Technology,NaN,Staff,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 5
33,1321967343,Legal,NaN,Department Lead,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 7
34,2206081204,People,NaN,Staff,Generation X (born between 1965-1980),Female,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 7
35,6285875694,Commercial,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 4
41,3968415666,Legal,NaN,Staff,Millennial (born between 1981-2000),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 4
42,4166850362,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Prefer not to answer,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 7
44,1948472863,People,NaN,Department Lead,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 8
46,2696474434,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 3
49,3618961108,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 8
52,7481772195,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 1
53,5044294817,Legal,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 6
...,...,...,...,...,...,...,...,...,...,...,...
16963,6588311032,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 1
16968,2850296334,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2
16970,6478560213,Information Technology,NaN,Staff,Prefer not to answer,Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
16971,9328885416,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
16972,6285007368,People,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
16975,4341029891,Finance,NaN,Staff,Prefer not to answer,Male,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 3
16976,9298970467,Information Technology,NaN,Department Lead,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 7
16977,3530464299,Legal,NaN,Department Lead,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 7
16978,1962504465,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6
16980,1914548336,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6
16982,7447366993,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2
16983,9858203307,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 8
16984,2375491161,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 1
16991,1220878407,Executive,NaN,Manager,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
16993,7103482882,Infrastructure,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6
16996,2102054017,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2
16997,6796580906,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 7
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 7
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 4
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 3
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 8
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 1
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 8
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6

In [71]:
df_answered.shape

(9664, 11)

In [72]:
df_answered= df_answered.groupby('Questions')['Respondent ID'].nunique().reset_index()
df_answered.rename(columns= {'Respondent ID' : 'Total_Respondent'}, inplace= True)
df_answered

      Questions  Total_Respondent
0    Question 1               119
1   Question 10               198
2   Question 11               164
3   Question 12               114
4   Question 13               108
5   Question 14               105
6   Question 15               114
7   Question 16               117
8   Question 17               135
9   Question 18               109
10  Question 19               157
11   Question 2               118
12  Question 20               105
13  Question 21               127
14  Question 22               160
15  Question 23               120
16  Question 24               195
17  Question 25               198
18  Question 26               193
19  Question 27               153
20  Question 28               119
21  Question 29               198
22   Question 3               117
23  Question 30               182
24   Question 4               161
25   Question 5               194
26   Question 6               196
27   Question 7               162
28   Question 8               190
29   Question 9               188

In [81]:
# adding this column to 'df_monkey_Edited' table

df_monkey_Edited_1= pd.merge(left= df_monkey_Edited, right= df_answered, how= 'left', left_on= 'Questions', right_on= 'Questions')

In [82]:
df_monkey_Edited_1

,Respondent ID,Division,Division(Other),Position_Level,Generation,Gender,Tenure,Employment_Type,Questions,Questions_&_Subquestions,Answers,Total_Respondent
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 4,119
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 5,119
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1,119
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 8,119
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 8,119
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,NaN,119
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3,119
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 4,119
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 2,119
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 7,119
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 5,119
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1,119
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3,119
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3,119
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3,119
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 4,119
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 2,119
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 1,119
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 5,119
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,NaN,119
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 2,119
...,...,...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 7,182
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 7,182
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 4,182
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 3,182
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5,182
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 8,182
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2,182
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 1,182
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5,182
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5,182
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6,182
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 8,182
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6,182
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182

In [83]:
# calculating how many respondent gave the same answers:

df_same_ans= df_monkey_Edited_1.groupby(['Questions_&_Subquestions', 'Answers'])['Respondent ID'].nunique().reset_index()
df_same_ans.rename(columns= {'Respondent ID' : 'Same_Answers'}, inplace= True)
df_same_ans

    Questions_&_Subquestions   Answers  Same_Answers
0        Question 1-Response  Answer 1            14
1        Question 1-Response  Answer 2            10
2        Question 1-Response  Answer 3            13
3        Question 1-Response  Answer 4            17
4        Question 1-Response  Answer 5            22
..                       ...       ...           ...
683    Question 9-Response 4  Answer 4            16
684    Question 9-Response 4  Answer 5            13
685    Question 9-Response 4  Answer 6            14
686    Question 9-Response 4  Answer 7            12
687    Question 9-Response 4  Answer 8            19

[688 rows x 3 columns]

In [86]:
#  Merging the 'df_same_ans' column in 'df_monkey_Edited_1' column:

df_final_table= pd.merge(left= df_monkey_Edited_1, right= df_same_ans, how= 'left', left_on= ['Questions_&_Subquestions', 'Answers'], right_on= ['Questions_&_Subquestions', 'Answers'])

In [87]:
df_final_table

,Respondent ID,Division,Division(Other),Position_Level,Generation,Gender,Tenure,Employment_Type,Questions,Questions_&_Subquestions,Answers,Total_Respondent,Same_Answers
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 4,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 5,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
5,3399511781,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,Answer 8,119,16.0
6,9860597462,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 8,119,16.0
7,1494621946,Infrastructure,NaN,Chief / Executive,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
8,8646387163,Information Technology,NaN,Manager,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3,119,13.0
9,2455127238,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 4,119,17.0
10,1905266879,Finance,NaN,Staff,Prefer not to answer,Female,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
11,7089369660,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),NaN,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 2,119,10.0
12,3397360934,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 7,119,11.0
13,6904821010,Other (please specify),Construction,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 5,119,22.0
14,9961006444,Executive,NaN,Staff,Prefer not to answer,Prefer not to answer,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
15,9736526482,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
16,8035211358,Commercial,NaN,Manager,Prefer not to answer,Prefer not to answer,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 1,119,14.0
17,2855503402,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
18,4136037887,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3,119,13.0
19,9624253323,Infrastructure,NaN,Staff,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 3,119,13.0
20,8546027678,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
21,3555213031,Legal,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 3,119,13.0
22,1754220060,Finance,NaN,Department Lead,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 4,119,17.0
23,9011744859,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 1,Question 1-Response,Answer 2,119,10.0
24,5875585727,Information Technology,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 1,119,14.0
25,9051604151,Commercial,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
26,6573346680,Commercial,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
27,4383571615,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,10+ years,Full time Employee,Question 1,Question 1-Response,Answer 5,119,22.0
28,5850350235,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,NaN,119,NaN
29,9526771290,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 1,Question 1-Response,Answer 2,119,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16998,3966690436,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
16999,8630148625,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17000,1264208927,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17001,9625886165,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 7,182,15.0
17002,9351204267,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 7,182,15.0
17003,1485638866,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 4,182,14.0
17004,9137601822,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17005,4910729713,Finance,NaN,Staff,Generation X (born between 1965-1980),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17006,8453428178,Commercial,NaN,Manager,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 3,182,11.0
17007,6903105973,Finance,NaN,Manager,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17008,2628194343,Executive,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17009,2254451126,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5,182,18.0
17010,1426184525,Finance,NaN,Staff,Baby Boomer (born between 1946-1964),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17011,1001882880,Infrastructure,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 8,182,14.0
17012,1941311372,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 2,182,9.0
17013,8569413026,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17014,5953471955,People,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 1,182,11.0
17015,3933988341,People,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17016,7963965247,Executive,NaN,Staff,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17017,9735550076,People,NaN,Staff,Generation X (born between 1965-1980),Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5,182,18.0
17018,5559071396,Port Security & Emergency Operations,NaN,Staff,Millennial (born between 1981-2000),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17019,8253262223,People,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17020,7325851635,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Prefer not to answer,3-5 years,Full time Employee,Question 30,Question 30-Response 3,Answer 5,182,18.0
17021,3370365802,Port Security & Emergency Operations,NaN,Staff,Generation X (born between 1965-1980),Female,0-2 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6,182,20.0
17022,2841747833,Information Technology,NaN,Staff,Millennial (born between 1981-2000),Male,0-2 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30,Question 30-Response 3,Answer 8,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30,Question 30-Response 3,Answer 6,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30,Question 30-Response 3,NaN,182,NaN

In [88]:
# exporting this table:
df_final_table.to_excel('Filtered Monkey Data.xlsx', index= False)